### ISSUE TITLE
Pair recording application

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#134]
This application will allow the user to experiment with 2 connected cells of a circuit.

**Comment by alex4200** [comment]
@pgetta : Let me know once you have a version of the App/GUI/Use case I can take a look at...

**Comment by alex4200** [comment]
From @pgetta:

>  I have something to show, but it’s not deployed yet. I’ll ask for a repository for this app and then there will be pretty tricky part to actually deploy it, because for such app OpenShift is the best choice, but app requires direct access to gpfs and this is not supported by OpenShift yet - will discuss with Core Services team ways to solve this. Hope to get somehow deployed app this week.

**Comment by alex4200** [comment]
Update from @pgetta 

> Now we  decided to try to copy the whole circuit with all necessary data into OpenShift created volume (waiting for CoreServices team to increase the quota - we need more then 200GiB per circuit). Now I’m testing script to make such a copy - picking what actually is crucial for application, trying to save as much space as we can - this also takes some time
> I’m about to finish testing of this script on my machine, as if we will be lucky and get increased quota from core-services team - maybe today in the evening - tomorrow morning app will be deployed.

**Comment by pgetta** [comment]
Update:

The app has been deployed to OpenShift with three separate instances:
```
http://bp-hippocampus-o1.ocp.bbp.epfl.ch/
http://bp-mouse-o1.ocp.bbp.epfl.ch/
http://bp-rat-ca1.ocp.bbp.epfl.ch/
```

Deployment for rat CA1 due to bigger size has few issues with memory, most of them are currently fixed, but still WIP. For the time being simulation doesn't work on that instance.

Last Friday we've received comments from NSE team members. With respect to those, feature to provide synaptic inputs along with some other fixes are being implemented now.

Next status update - Monday 30th of April, in a week.

**Comment by mmigliore** [comment]
Nice!
However, when I click on a cell I expected to see only cells which are  
connected to that cell in input or output.
Instead I do not see any change in the visualization.

Cheers
Michele


Pavel Getta <notifications@github.com> ha scritto:

**Comment by pgetta** [comment]
There is `Connectivity filter` on a side-panel that  can be used to filter cells based on their connections (afferent, efferent, both).

I’ve noticed an issue with a backend for  `http://bp-rat-ca1.ocp.bbp.epfl.ch/` <http://bp-rat-ca1.ocp.bbp.epfl.ch/%60>, it has been restarted, so that feature now works.

UI still needs some improvements to be done. Concerning connection filers: maybe we should add some of them automatically when one select a cell. Does this sound like a good idea? If it does, which types of connected cells do we need to show by default: with afferent / efferent / afferent and efferent / afferent or efferent connections?


Regards,
Pavlo

**Comment by mmigliore** [comment]
I see, all clear now.

> UI still needs some improvements to be done. Concerning connection  
> filers: maybe we should add some of them automatically when one  
> select a cell. Does this sound like a good idea? If it does, which  
> types of connected cells do we need to show by default: with  
> afferent / efferent / afferent and efferent / afferent or efferent  
> connections?

afferent AND efferent is a good choice.

Also, I see that the visualization of  
http://bp-hippocampus-o1.ocp.bbp.epfl.ch/
shows something that does not have anything to do with what one  
expects for hippocampus.
This should not be included in the list available for the reviewers.

Best
michele


>
>
> Regards,
> Pavlo
>

**Comment by alex4200** [comment]
Application is online ...
