### ISSUE TITLE
Unable to continue workflow

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#175]
### Expected behavior

Able to continue a saved workflow

### Actual Behavior

After loading a saved workflow, it does not indicate what has been done already, nor can I continue the workflow (unable to click on 'Upload file' in 'Optimization files', for example).

![selection_181](https://user-images.githubusercontent.com/12729291/35846692-f58c3ff0-0b17-11e8-948c-e75712de8201.png)

### Steps to reproduce the problem

- Start a new Collab
- Select "Initiate a new workflow"
- Select "Cell Optimization"
 - Select "Feature Extraction: Upload Files", upload a file
- Save workflow
- Close tab
- Reopen Collab
- Load workflow

**Comment by lbologna** [comment]
Hello,

the steps already completed are indicated by the fact that the bars on the bottom of the panels are green. The user can also download the files concerning each completed steps through the "Download" links.

In this specific case, the optimization had been previously submitted, so, in order not to allow a second submission with the same workflow id, all the other operations are blocked.
If the user wants to use again the files/folders adopted in the workflow downloaded from the storage, she/he can clone the workflow (via the button on the top bar) and all the buttons will be active again (because the workflow will have a new id)

**Comment by alex4200** [comment]
@lbologna : I am not quite sure I understand. I created a new workflow, and have not chosen any optimization file. Why would that item be blocked?

**Comment by alex4200** [comment]
Works now
