### ISSUE TITLE
"Optimization settings" step not saved?

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#178]
### Expected behavior

When I load a workflow where all three boxes has been green ("Feature extraction", "Optimization files" and "Optimization settings") I expect them to be 'green' again.

### Actual Behavior

The "Optimization settings" is red. I have to open that step and press 'apply' again. 

![selection_200](https://user-images.githubusercontent.com/12729291/35977036-46765f42-0ce2-11e8-8d76-9b2b6d51277f.png)

### Steps to reproduce the problem

- Create a new workflow
- Provide all required information for the boxes "Feature extraction", "Optimization files" and "Optimization settings" and save the workflow
- Reload the same workflow

**Comment by lbologna** [comment]
Hello,
the "Optimization settings" panel's bar becomes green when all the fields are filled, including the user's credentials needed to access hpc systems.
Given that the workflows are saved in the collab storage, the credentials are not stored for privacy reason. This is why the bar stays red when fetching a previous workflow.

In order to make the user aware that the settings (if previously saved) have been correctly fetched and only the credentials have to be reinserted, I changed  the status message to "HPC system and credentials NOT set".

Could you please check again?

Thanks.

**Comment by alex4200** [comment]
Ok, sounds good to me...
