### ISSUE TITLE
HH cloning does not seem to work in all cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#185]
### Expected behavior

When cloning a workflow, I expect all the 'green' steps to be green after the cloning.

### Actual Behavior

In the first workflow all the steps were green (including 'Optimization results'), but after cloning its red with an error "NO simulation .zip file or NO correct output from optimization"

Before cloning:

![selection_220](https://user-images.githubusercontent.com/12729291/36300081-1ddceb86-1300-11e8-8232-d772219dd75d.png)

Right after cloning:

![selection_221](https://user-images.githubusercontent.com/12729291/36300091-243cacfa-1300-11e8-8ce2-8aeabc9972d4.png)

### Steps to reproduce the problem

Create a workflow with all the steps green, then click on 'Clone'.

**Comment by lbologna** [comment]
This should be fixed now. Could you please test again? Thanks

Please note that the optimization settings bar will always be red when a workflow is fetched from the storage (even if it was green when the wf was saved). This is due to the fact that the credentials are not stored to the storage for security reasons. Nonetheless, the other parameters (if previously set) are correctly fetched and the message "Settings retrieved. Credentials NOT set" is shown  to the user.
