### ISSUE TITLE
Guidebook documentation for Single Cell Building

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#195]
In the Guidebook the documentation for the hippocampal cell model use cases are listed under a 4th level header (i.e. a header with four digits like 2.3.2.1). 

However, in the rest of the guidebook the use cases are under a 3-level header (i.e. a header with three digits). I would strongly argue to do that the same for the hippocampal cell model use cases; then it looks more structured and we can avoid having 5 level headers...

**Comment by clupascu** [comment]
I think that, unfortunately, the 4th level header for the hippocampal cell model use case (as for the jsons in hippocampal neurons, or the graphical user interface and the Electrophysiological data for the Feature Extraction Graphical User Interface) can't be avoided because of the complex structure of the above mentioned use cases.

**Comment by alex4200** [comment]
Will close this ticket, as this is not an important issue at this time.
