### ISSUE TITLE
JURECA run mode ended FAILED

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#230]
### Expected behavior

I am able to run on JURECA as well

### Actual Behavior

After clicking on "Run JURECA Simulation" and some small time I get a status FAILED:

![selection_258](https://user-images.githubusercontent.com/12729291/37145878-6bf90ee0-22c2-11e8-90be-2830ac50af4b.png)

### Steps to reproduce the problem

Run default case.

### Environment

I have access to JURECA.

**Comment by clupascu** [comment]
Do you have some files in the storage for this job? Like a log file?

**Comment by alex4200** [comment]
Not sure. I have started many jobs, and I do not know what job I have started -> #229

**Comment by clupascu** [comment]
You should find them in the folder results. This is the folder for the outputs from Jureca.

**Comment by mmigliore** [comment]
Hi Everybody,
I do not know if this is relevant to this issue but
jobs on jureca should run ONLY using the vsk25 account and the booster  
partition, NOT bp0 accounts.
bp0 accounts have been frozen because there is no more computing time left.
Best
Michele


clupascu <notifications@github.com> ha scritto:

**Comment by clupascu** [comment]
I am mapped as bp0 on JURECA. @alex4200 was able to run the job on JURECA anyway. I don't know though how he is mapped on JURECA.

**Comment by mmigliore** [comment]
everybody should be mapped with vsk25

clupascu <notifications@github.com> ha scritto:

**Comment by clupascu** [comment]
I asked today to be mapped with my vsk25 account. It seems that since a couple of days, all our accounts are automatically enabled for UNICORE, and we can select the one that we want using a special HTTP header.

X-UNICORE-User-Preferences: uid:vsk25*

Still, the vsk25* accounts have access to the "booster" part of JURECA, which is not yet available via UNICORE. They are trying to fix that.

**Comment by clupascu** [comment]
The vsk25* accounts on Jureca are now available via UNICORE as well.

We need however to specify the "booster" partition in the resources section of our job like this:

"Resources" : {
  "Queue": "booster",
}
I will modify the notebooks now.

**Comment by clupascu** [comment]
This should be fixed now. Can you please test again with your vsk25* account? Thanks.

**Comment by alex4200** [comment]
Yes its working
