### ISSUE TITLE
Job submission failed

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#244]
### Expected behavior

Job is executed correctly

### Actual Behavior

Job failed:

![selection_270](https://user-images.githubusercontent.com/12729291/37699502-19b394c2-2ce8-11e8-9740-1eb9e2aedefa.png)

Some further investigation reveals the following problem: 

Wed Mar 21 09:10:27 CET 2018: TSI reply: FAILED.', u'Wed Mar 21 09:10:27 CET 2018: Submit attempt 1 (of 3) failed: de.fzj.unicore.xnjs.ems.ExecutionException: Submission to classic TSI failed. Reply was <TSI_FAILED: Your project is not allowed to submit batch jobs within this quota pool:llsubmit: 2512-052 Submit Filter /bgdata/admin/loadl/extensions/filter: rc = 1.:llsubmit: 2512-056 Unable to process the job command file "TSI_temp_file_24133".:llsubmit: 2512-051 This job has not been submitted to LoadLeveler.:\n> [XNJS error 11]', u'Wed Mar 21 09:10:37 CET 2018: Incarnated resources: [CPUsPerNode=16.0, MemoryPerNode=1.6384E10, Nodes=512.0, CPUTime=86400.0]'

Should I run the jobs on JUQUEEN? As this cluster is going to be discontinued, I thought the way to go was JURECA. 

### Steps to reproduce the problem

Run the notebook step-by-step (with the fix proposed in #243 ).

**Comment by SelezioneCasuale** [comment]
We don't have an account on JURECA at the moment and I'm not sure that NEST is installed or properly configured there in order to run through UNICORE. 
So please try JUQUEEN

**Comment by alex4200** [comment]
The JUQUEEN job fails as mentioned above. I have the following UIDs for JUQUEEN:

[bp000128:pra09810, active=bp000128]

Maybe I need to change something in the job submission?

Also, as far as I know JUQUEEN is decommissioned very soon. I strongly suggest to make that use case work on JURECA, because the SGA1 reviewers might have JURECA accounts...

**Comment by SelezioneCasuale** [comment]
I see. So JUQUEEN is going to be dismissed *before* the reviewers can test
our Use Cases?
Actually I was not aware of this, I'm sorry.
 By the way, as I said, we don't have an account on JURECA. Do you know if
there is a (possibly fast) way to have one?
We have an account on JULIA but NEST is not working there.

Also, I'm trying to install NEST on the Collab - I also contacted the
Collab team; they told that they about the NEST issue and that they will
solve it asap.  - but I've some issues; in order to do it,
I should be able to use sudo apt-get install to install python-dev, which
is required to compile some C files for nest.python binding. However, of
course I'm not a sudoer and so I can't use apt-get install from a
notebbok within the Collab. Is there any work-around for this problem?

Having NEST running on the Collab would allow, at least, to run the 'local'
Use Case.

Sorry for all the questions and thanks in advance for your help

Best
Stefano

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-22 10:00 GMT+01:00 alex4200 <notifications@github.com>:

**Comment by SelezioneCasuale** [comment]
I see. So JUQUEEN is going to be dismissed *before* the reviewers can test
our Use Cases?
Actually I was not aware of this, I'm sorry.
 By the way, as I said, we don't have an account on JURECA. Do you know if
there is a (possibly fast) way to have one?
We have an account on JULIA but NEST is not working there.

Also, I'm trying to install NEST on the Collab - I also contacted the
Collab team; they told that they about the NEST issue and that they will
solve it asap.  - but I've some issues; in order to do it,
I should be able to use `sudo apt-get install` to install python-dev, which
is required to compile some C files for nest-python binding. However, of
course I'm not a sudoer and so I can't use apt-get install from a
notebook within the Collab. Is there any work-around for this problem?

Having NEST running on the Collab would allow, at least, to run the 'local'
Use Case.

Sorry for all the questions and thanks in advance for your help

**Comment by alex4200** [comment]
@SelezioneCasuale Regarding JUQUEEN and JURECA: I advise to get an account on JURECA quickly, I  think the following link can be used to apply for an (vsk25) account on JURECA:

https://dispatch.fz-juelich.de:8812/nic_account_ident/back=/RESOURCES&xxlang=english

@mmigliore should be able to help as well...

Regarding NEST: Collab is ready to deploy a new notebook image fixing the NEST issue, but it will reset the container for everyone. I suggest to talk about this on the Monday meeting...

**Comment by SelezioneCasuale** [comment]
@alex4200  Thanks; yes we contacted Michele and  now I have access to JURECA; I also have a bind for UNICORE, so I can submit jobs form Collab. Just have to figure out how to use NEST from there - we're working on it.

**Comment by jdcourcol** [comment]
New notebook sent (local version). To be validated by @alex4200.
