### ISSUE TITLE
multiple copies of the same model in the model catalog

### ISSUE THREAD

**Issue by mmigliore** [cnr-ibf-pa/hbp-bsp-issues#265]
### Expected behavior
there should be only one entry of each model in the catalog
### Actual Behavior
there are many entries for the same model
### Steps to reproduce the problem
enter the model catalog and search, for example, for "a1-2". There are many replica of the same model, 5 of them pointing to exactly the same zip file.

**Comment by appukuttan-shailesh** [comment]
This (in all likelihood) came about owing to the repeated runs of the SP6 online usecases. The ones that correspond to the entries in the "Model Artefacts" spreadsheet all have the 'Organization' = `HBP-SP6`, and for these only one entry exists per model. Thus, the filter can be set appropriately to view these entries.

I agree this needs to be resolved, but I am not sure how best to handle the problem of duplicates. If we force retain only one version per model, then any validation run by any user (including hbp external users? as models and usecases are public) would get 'linked' to the entries corresponding to the spreadsheet. Are we ok with this, or do we prefer to link only validations run by model owners and collaborators? If the latter, then the models should be set as `private`; but then we are likely to again end up with a duplicate `public` version from runs of the usecases by other users.

@apdavison : your thoughts...?

**Comment by apdavison** [comment]
I think we should have only one entry per model and per model instance, and in principle it is a good thing if all validations of a model (run by whoever) are linked to that model.

The only potential problem is that if someone modifies the code for a validation test and introduces a bug, this could give a bad result for a model and make the model look bad. The solution to this problem is to:

1. have versioning for tests (which we have, although we should reflect on how we ensure that any differences in code are reflected in a difference in version, through using Git hashes for example);
2. allow filtering validation test results so as to exclude bad versions of tests (we don't yet have this, perhaps add a flag to each model version allowing it to be marked as "invalid" (or invert this, and mark versions as "approved").

**Comment by appukuttan-shailesh** [comment]
All the "duplicates" have either been renamed with "[COPY]" prefixed to their old names, or deleted (once that were known to have been created for running sample tests). This now ensures that all the entries in "Model Artefacts" spreadsheet have only a single exact match in the Model Catalog app. Let us know if any additional changes are required.

**Comment by jdcourcol** [comment]
@mmigliore : I would suggest to remove all the [COPY] ones. This app is going to be accessed by the reviewers for reviewing the models. Having these "[COPY]" looks dirty or looks "test" environment.

**Comment by appukuttan-shailesh** [comment]
@jdcourcol , @mmigliore : I have now deleted all the duplicates. The model catalog should thus look much neater. Do take a look and let me know if you find anything that needs fixing.

**Comment by mmigliore** [comment]
I still see many entries with identical names but with somewhat different content (e.g. str-fs-161205_FS1-BE37A-20180212 or msn_d1_all-6-20170524)

**Comment by appukuttan-shailesh** [comment]
That's right... the above updates were only applicable to the hippocampal models. Shall purge the database of duplicates for other domains over the next couple of days.

**Comment by appukuttan-shailesh** [comment]
@alex4200 : This is now resolved. Duplicates have been deleted. 

Note: only 4 entries with same name continue to exist, but this was based on data provided by modeling teams and not to be deleted. The modelers can update the names at any time via the model catalog.

**Comment by alex4200** [comment]
@appukuttan-shailesh where and how can I check this now?

**Comment by alex4200** [comment]
So far it looks fine....
