### ISSUE TITLE
StorageForbiddenException in Cell Placement Cerebellum

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#266]
### Expected behavior

A non HBP user should be able to use this use case as well

### Actual Behavior

A non-HBP user gets the following error when running the use case

```
Writing 'save_name' (str) to file 'to_connectome.txt'.
Writing 'volume_base_size[0]' (float64) to file 'to_connectome.txt'.

StorageForbiddenExceptionTraceback (most recent call last)
<ipython-input-14-0e9462cbfa17> in <module>()
      4     conn_file = bsp_folder + 'to_connectome.txt'
      5     if client.storage.exists(conn_file):
----> 6         client.storage.delete(conn_file)
      7     client.storage.upload_file('to_connectome.txt',conn_file, 'text/plain')

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/storage_service/client.pyc in delete(self, path)
    257             self.api_client.delete_folder(entity['uuid'])
    258         elif entity['entity_type'] == 'file':
--> 259             self.api_client.delete_file(entity['uuid'])
    260 
    261     @classmethod

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/storage_service/api.pyc in delete_file(self, file_id)
    993 
    994         self._authenticated_request \
--> 995             .to_endpoint('file/{}/'.format(file_id)) \
    996             .delete()
    997 

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in delete(self)
    233             Any exception parametrized with the `throw` method
    234         '''
--> 235         return self.__send('DELETE')
    236 
    237     def put(self):

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in __send(self, method)
    258         )
    259 
--> 260         self.__throw_if_necessary(response, self._throws)
    261 
    262         if self._return_body:

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in __throw_if_necessary(response, throws)
    270             args = should_throw(response)
    271             if args is not None:
--> 272                 raise exception_class(args)
    273 
    274     @staticmethod

StorageForbiddenException: You are forbidden to do this.
```

### Steps to reproduce the problem

Run the use case as a non-HBP member

### Solution

The problem is 1. a non-HBP member does not have write access to a Collab, even when its open and 2. the use case does probably not do what is expected. 

_Explanation:_

In the second-to-last cell the script is trying to create/copy data to files in a Collab. The current used Collab is Collab "8124". Why would a user copy its data to that Collab? For me that does not make sense; the data should be copied to the Collab the user has created or is using. 

_Suggestion:_

I suggest the following changes to the second-to-last cell:

```
if save:
    %store save_name > to_connectome.txt
    %store volume_base_size[0] >> to_connectome.txt
    this_folder = os.path.join(get_collab_storage_path(), "CellPlacementCerebellum")
    client.storage.mkdir(this_folder)
    conn_file = os.path.join(this_folder, 'to_connectome.txt')
    print conn_file
    if client.storage.exists(conn_file):
        client.storage.delete(conn_file)
    client.storage.upload_file('to_connectome.txt',conn_file, 'text/plain')
```

That creates a new folder in the CURRENT Collab to which the user has access, and copies all relevant files into that new folder

Changes to the LAST cell:

```
if save:
    # Create a .hdf5 file to store data; .hdf5 is the 'standard' format 
    f = h5py.File(save_name, 'w')
    f.create_dataset('positions', data=data_matrix)
    f.close()
    new_file = os.path.join(this_folder, save_name)
    
    # Create also a .dat file; at the moment, this is the only viable solution for sending jobs on HPC
    to_dat_fname = save_name.split('.hdf5')[0]+'.dat'
    df = pd.DataFrame(data=data_matrix.astype(np.float))
    df.to_csv(to_dat_fname, sep=' ', float_format='%+.8e', header=False)
    to_dat_file = os.path.join(this_folder, to_dat_fname)

    ....
```

**Comment by SelezioneCasuale** [comment]
Ok, we understand the problem.
The Placement and Connectome use cases were conceived to be executed sequencially; the output of the placement is represented by (1) a hdf5 file and (2) a .txt file with the name of the just created hdf5 file. When, in turn, you run the Connectome notebook, this .txt is readen and and the Connectome will point to the **last** .hdf5 file that has been created with the Placement. Eventually, the Connectome update the .hdf5 file with connection data.  All this read / write process through the two use cases should rely upon a common storage. That's why we decided to give a fixed collab storage path, '8124'., where the user can write a file from, say, a Collab _X_ and then retrieve the very same file from a new Collab _Y_. 
But as you mentioned, a non-HBP member cannot write files directly into our Collab. So, I think  that theer are two possible solutions

1. We explicitly inform the user that the Placement and Connectoem should be opened _in the same_ Collab. Hence, when the user test the Placement use case, a new collab named _test_ , for example, must be created. Then, when the Connectome is tested, the user should search for the _test_ collab and not create a new one 
2. The two use cases can be made independent from each other. So, the Connectome will take as input the ouput of the last Placement run; instead, we can prepare some standard .hdf5 files for the Connectome and the user can choose among them, without the need to run a Placement before or to keep track of the lastly created Collab. 

Maybe we can discuss this better on Monday; btw, my personal opinion is that there should be less chances of error for the user with second option.

**Comment by alex4200** [comment]
@SelezioneCasuale : What about my suggestion? It should be the most userfriendly, but not sure how difficult to implement it:

- The Placement notebook creates the results in the storage in some folder (e.g. 'CerebPlacement/results.hdf5')
- The Connectome notebook checks if such a result exists in the current Collab. 
- If so: the user is presented with three options:
  1. Use the results in the Collab
  2. Chose from some standard hdf5 files
  3. Provide path to other results (maybe from a different notebook).  
- If not: Just the two last options.

That way the user knows exactly what he/she is doing and its transparent. 

What do you think?

**Comment by SelezioneCasuale** [comment]
@alex4200 @elisamarenzi 
Alex, I think your suggestion is great; I try now to implement it and see exactly which difficulties may occur. 
Thanks a lot

**Comment by SelezioneCasuale** [comment]
@alex4200 @elisamarenzi 
Alex, issues #266 and #267 should now be solved. Please let us know if there are still some errors. 
In the end, we opted for a easier (to implement) solution for the Connectome problem; if there is a .hdf5 file in the current storage, that one will be used for connectome building; otherwise, the user is pointed to a standard .hdf5 with a  200x200 scaffold. We'll improve it in future, of course. Please, let us know if you think it's fine.

**Comment by alex4200** [comment]
Ok seems to work so far, thanks
