### ISSUE TITLE
Backspace removes more than one digit for 'time step'

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#299]
### Expected behavior

To be able to edit the time step in the text box just I expect to edit something

### Actual Behavior

I place the cursor at the end of the text '0.01', press the backspace key, but then the content of th box becomes '0'. The backspace seems to remove 3 instead of 1 character

### Optional infrastructural data (user, platform, browser, environment, ...)

Chrome, Mac

**Comment by pgetta** [comment]
This is behaviour of input component which is trying to have correct value within programmed range no matter what you input.

Nonnumeric values are being replaced with previous valid values.
Out of range values (in respect to min and max allowed in current input) are being replaced with closest valid values.

Also, numbers in all inputs can be changed by pressing on `up` and `down` buttons, step is different for each feature and adjusted to range of possible values.

So in your case when you remove `1` from `0.01`, leftover `0.0` is not a valid number, that's why input component replaces this value with zero.

Let me know if this is something that should be fixed - it's feasible, but we will have to replace all inputs of the app, because current input component module doesn't support any changes in it's behaviour.

**Comment by alex4200** [comment]
Not a bug then, but 'works by design'
