### ISSUE TITLE
Implementing two new models for BlueNaaS

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#349]
As a request of @SteMasoli he wants his two models be implemented into a list of models to be selected in the BSP (for BlueNaaS):

Single section model.
https://blue-naas.humanbrainproject.eu/#/model/grc_mono 
Temperature = 30 
Vinit = 80
Current clamp = from 0.01 to 0.03nA
![selection_501](https://user-images.githubusercontent.com/12729291/48259083-3470f980-e417-11e8-9caf-5d70c4083806.png)

Multi section model
https://blue-naas.humanbrainproject.eu/#/model/grc_multi
Temperature = 30 
Vinit = 70
Current clamp = from 0.01 to 0.03nA
![selection_503](https://user-images.githubusercontent.com/12729291/48259086-376bea00-e417-11e8-8c40-3fd8c64c3316.png)

The two models could be added to the list of models (Luca is handling so far I know)
![selection_495](https://user-images.githubusercontent.com/12729291/48259150-684c1f00-e417-11e8-89db-a98971c934a3.png)

OR we could insert a new selection (as it is done when selecting the "Small Circuit In Silico Experiments" use case, but naming instead e.g. "Please select a region" and the you can select 'hippocampus' and 'granule cells' or something):

![selection_504](https://user-images.githubusercontent.com/12729291/48259209-916caf80-e417-11e8-880c-04bc72dea64a.png)

**Comment by SteMasoli** [comment]
@genric I wrote to Luca about the way they use to upload the models. Have I to create a new specific container? The models, to be uploaded, will be a dozen or more.

**Comment by clupascu** [comment]
@genric Where are you fetching the list of models to be selected in the BlueNaaS from? Are you still using https://github.com/lbologna/bsp_data_repository/?

**Comment by genric** [comment]
I am currently trying to make hippocampus models available as MINDS dataset over here: https://www.humanbrainproject.eu/en/explore-the-brain/search/?facet_type[0]=Dataset
I think this is how all models will be published in the future: using HBP knowledge graph(NEXUS). If you want, we could try integrating your models as well. For that I would need the set of zip files(which you tested with BlueNaaS) or a git repository url with all your models you wish to publish. Have in mind that this integration might take some time(weeks probably). So if you need this urgently we could just extend the existing list and do it the old way.

**Comment by jdcourcol** [comment]
@genric be careful as @clupascu data are 'optimization' not just single cell model.

**Comment by genric** [comment]
@clupascu Yes, they were fetched from that repository. And the ones I'll be uploading to HBP NEXUS I'll fetch from there.

**Comment by genric** [comment]
@jdcourcol Yes, in the first iteration single cell models will contain only necessary information to load them to BlueNaaS. Later we can attach more metadata regarding optimization.

**Comment by clupascu** [comment]
@genric As GitHub recommends repositories to be kept under 1GB each and our repository is already at 800Mb, we want to add new models to the CSCS container that was created for the optimizations https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/hippocampus_optimization/ (even if there is no versioning here). Can you fetch the models from a container too?

**Comment by genric** [comment]
@clupascu Yep, I have the access.
Actually this container can be attached to the knowledge graph dataset as raw data. So people who wish to access optimization metadata can follow the link.

**Comment by apdavison** [comment]
@genric Please note that making models available through the HBP Knowledge Graph is something we are also working on in my team, as part of our work in SP5. We are currently migrating the Model Catalog to the Knowledge Graph, so that in future there will be two ways to access information about models: through the Model Catalog API and directly through the KG APIs.

We should coordinate our work on this to avoid duplication of effort.

For the time being, even before completing the KG integration, the list of models could (should, I think) be obtained through the Model Catalog API - see https://hbp-validation-framework-api.readthedocs.io/en/latest/models.html#list-model-descriptions-that-satisfy-specified-filters and let us know if the filters we have are inadequate.

**Comment by clupascu** [comment]
@apdavison Are you fetching the models in the Model Catalog from github too?

**Comment by apdavison** [comment]
@clupascu We do not automatically update the Model Catalog from github, but I understood that all models from the github repository were imported into the MC, and that you were no longer using github for this purpose. @appukuttan-shailesh can you comment further?

(Maybe we could all work on this together at the CodeJam in a couple of weeks. @genric will you be going to the CodeJam?)

**Comment by appukuttan-shailesh** [comment]
@apdavison : Yes as part of end of SGA1 activities, and subsequently for the live-paper, we had registered all (I believe we covered ALL) models from the CSCS containers on the model catalog. We have stopped keeping track of the GitHib repository now (unless having specific requests for the same).

@genric : We had discussed some weeks ago about integrating BlueNaaS with the model catalog. At the time, we had proposed taking this up at the CodeJam later this month. Hope we can get atleast something preliminary working.

**Comment by genric** [comment]
@apdavison I see, thanks for the update!

**Comment by genric** [comment]
@appukuttan-shailesh yeah, and recently I've learned about these MINDS datasets, so I was trying to make the models indexed and available in the HBP KG search. At the CodeJam there will be also people from the HBP KG team, so looks like it will be a pretty busy CodeJam :) looking forward to it!

**Comment by SteMasoli** [comment]
I hope there will be some documentation for those, like me, that will not attend the CodeJam.

**Comment by appukuttan-shailesh** [comment]
Moving the discussion back to here:

@SteMasoli : I saw the google doc.... so I suppose we are referring to rows 60, 61 and 62. I have verified that the models are publicly accessible and in BlueNaaS appropriate format. I shall upload these three models to the model catalog and let you know.

Regarding (from #351):
> The file already on the mode catalog need to be deleted.

I don't think we need to delete these. The model catalog is intended to retain old data, and not just the latest models. Do let us know if there are other reasons for wanting to delete these.

@alex4200 : Somebody needs to handle the adding of these models to the 'UseCase' list (see Figs. 3 and 4 in first post). Not sure who handles this.

**Comment by SteMasoli** [comment]
@appukuttan-shailesh 

> I shall upload these three models to the model catalog and let you know.

Thank you.

> Do let us know if there are other reasons for wanting to delete these.

To avoid misunderstandings when an user will search for a model, in the model catalog, and will find the single files instead of the packages for BlueNaaS. 

>  Somebody needs to handle the adding of these models to the 'UseCase' list. 

This can be work around for the previous comment. 
Having the BlueNaaS models accessible from the BSP will solve the problem of searching in the model catalog and will let me define the appropriate parameters to do the simulations.

**Comment by appukuttan-shailesh** [comment]
@SteMasoli : The three models have been uploaded to the model catalog, you can find them here:

1) Granule cell - Mono compartmental
https://collab.humanbrainproject.eu/#/collab/9136/nav/77077?state=model.527191ca-8385-4aac-b08c-3bce022fc5cc

2) Granule cell - Multi compartmental
https://collab.humanbrainproject.eu/#/collab/9136/nav/77077?state=model.0c97cd83-24fd-4782-bdea-2affacc6863e

3) Purkinje cell - Multi compartmental
https://collab.humanbrainproject.eu/#/collab/9136/nav/77077?state=model.d3a1a6f7-d4c6-4e4a-b1d8-76e470f20862

Do take a look and see if they are ok. If not, you can edit the entries on the above links (click the "Edit" button).

I haven't deleted the older entries as they seemed to be different from the current entries (e.g. the species was 'Rat' for some of the older entries). We could possibly decide on the deletion later.

@genric : As replied via email, we are now able to use public CSCS storage container URLs to launch models in BlueNaaS. Thanks for getting this to work. The model catalog is expected to have this BlueNaaS feature implemented in around 2 weeks (you can track progress here: https://github.com/HumanBrainProject/hbp-validation-framework/issues/228).

@alex4200 : 
> Somebody needs to handle the adding of these models to the 'UseCase' list (see Figs. 3 and 4 in first post). Not sure who handles this.

Might be good to have this sub-task assigned to someone so that it isn't overlooked.

**Comment by appukuttan-shailesh** [comment]
@antonelepfl : Here is the docs for the Model Catalog REST API:
https://hbp-validation-framework-api.readthedocs.io

**Comment by antonelepfl** [comment]
@genric @appukuttan-shailesh I was checking the content of the models and I saw there is a morphology picture but I don't find the traces for each model as image.
In Github we had the traces images + the morphologies (Fig 3).
Is it somewhere else than associated with the models?

**Comment by appukuttan-shailesh** [comment]
The traces were not uploaded to the model entries previously. Just last week @clupascu proposed that we could upload these as well. We shall ensure that this is updated for the future models, and the models relevant to the described on the [live paper](https://cnr-ibf-pa.github.io/hbp-bsp-live-papers/migliore_et_al_2018/migliore_et_al_2018.html).

Do you have a specific use for these images? Currently they are provided on the model catalog entries mostly as added info.

**Comment by antonelepfl** [comment]
Specific use I think is the model list that I present before selecting a use case (Fig 3)

**Comment by appukuttan-shailesh** [comment]
How do you intend to shortlist the models to be displayed for the use case? I suppose it won't be feasible (or appropriate?) to display every entry from the model catalog as these would be numerous.

**Comment by appukuttan-shailesh** [comment]
@clupascu, @antonelepfl
Update: The responses image has now been uploaded for all the models relevant to the [live paper](https://cnr-ibf-pa.github.io/hbp-bsp-live-papers/migliore_et_al_2018/migliore_et_al_2018.html).

**Comment by antonelepfl** [comment]
Cool thank you @appukuttan-shailesh

**Comment by antonelepfl** [comment]
Is there any remain topic here? Can we close this ticket?
BTW the models are in dev version #360

**Comment by alex4200** [comment]
For me its ok to close this ticket...
