### ISSUE TITLE
Job name and date out of sync in Synaptic Events Fitting

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#431]
### Expected behavior

Correct date for a given job. 

### Actual Behavior (please include screenshot if possible)

The job names and job dates are out of sync. Here is what is shown:

![Selection_687](https://user-images.githubusercontent.com/12729291/56878362-04182880-6a54-11e9-893d-d722d8c3ed07.png)

and here are debug messages showing the expected date for the marked job:

![Selection_688](https://user-images.githubusercontent.com/12729291/56878371-109c8100-6a54-11e9-9be9-19d14b923712.png)

I have added the following two lines in the code:

```
# line 337:
print job_name, job_submissiontime 
# line 388:
print job_submissiontime_list[indexes[i]], parser.parse(job_submissiontime_list[indexes[i]]).astimezone (pytz.timezone('CET')).strftime("%d/%m/%Y %H:%M:%S")
```

### Steps to reproduce the problem

1. Run the Synaptic Events Fitting Analysis Notebook
2. Select NSG as system

**Comment by clupascu** [comment]
@alex4200 I believe this is because I wanted to show only the jobs submitted with NEURON75 (the fitting jobs), while the other ones (submitted presumably with the notebook to test hpc status) are submitted with NEURON73. I may continue to display all the jobs or only the ones connected with the synaptic fitting. I believe the second one is better. Do you agree?

**Comment by clupascu** [comment]
It should be fixed now. Can you please test again? Thanks.

**Comment by alex4200** [comment]
Seems to work, merged to PROD.
