### ISSUE TITLE
500 Server error Jureca

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#440]
Hi @BerndSchuller ,

Jureca was down yesterday but today I am able to connect to it, however when I try to launch a job with Unicore I get:
```
errorMessage: "Could not submit job: eu.unicore.security.AuthorisationException: There are no accessible targetsystem factories for: Name: CN=ANONYMOUS,O=UNKNOWN,OU=UNKNOWN↵Xlogin: uid: [], gids: [addingOSgroups: true]↵Role: anonymous: No role information available↵Security tokens: Delegation to consignor status: false, core delegation status: false↵Message signature status: UNCHECKED↵Client's original IP: 128.179.154.220 Please check your security setup!"
```
Could it be that you need to restart something because the maintenance?
Thank you Bernd

**Comment by BerndSchuller** [comment]
There still are problems with JURECA, no idea what exactly is going on, but filesystem operations on the GPFS mounts are super slow. Not much I can do about that, I hope the systems guys fix it as they usually do :-)
The ANONYMOUS stuff however is weird, since the authentication systems appear to be working. If you check the /rest/core endpoint you should see your usua user ID and project.

**Comment by antonelepfl** [comment]
Apparently is slowly being recovered. Thanks for the update and yes I confirm that /rest/core gives the correct information.
