### ISSUE TITLE
Validation usecases: Unnecessary package installs 

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#463]
### Expected behavior

Required versions of packages should only be installed when they are required, i.e. when the version is different from the installed one.

### Actual Behavior (please include screenshot if possible)

It seems like a package will be installed even if the version is fine. This affects every validation use case, and the problem is within the first code cell. 

### Steps to reproduce the problem

Depends on the user settings - but usually just run the first cell and compare the installed packages before and after

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV

**Comment by appukuttan-shailesh** [comment]
This shouldn't be happening as we have the following check in place inside `install_req_packages()`:
```
if not pkg_vinfo["min_version"] or current_version < parse_version(pkg_vinfo["min_version"]) or current_version > parse_version(pkg_vinfo["install_version"]):
```

Also, I am demanding for exact versions of the packages (and not just any version >=) as some of these packages are often changing such that they are not backwards compatible at times. We have seen many such situations with these usecases over the past 2 years, and it is a pain to rectify them for each new version. So we decided to tie these to specific versions of the packages.

**Comment by alex4200** [comment]
In the DEV usecases you also have this line in the first code cell:

                    "hbp_validation_framework" : {"min_version": "", "install_version": "https://github.com/appukuttan-shailesh/hbp-validation-client@usecase_patching"},

which triggers the framework to be reinstalled although the version remains the same. It is also an example where you do not have an explicit version number. 

Suggestion: Do a separate pip install

**Comment by appukuttan-shailesh** [comment]
This was intended. Some temporary patchwork was required to make the usecases run while the KG backend isn't completely ready (minor API changes to be made/tested). 

Once the APIs are completely ready, I will make a new pip release and update the first cell in the usecase notebooks to reflect the latest version number.

**Comment by rmiglior** [comment]
1Inviato da smartphone Samsung Galaxy.ķo k
-------- Messaggio originale --------Da: appukuttan-shailesh <notifications@github.com> Data: 02/10/19  17:18  (GMT+01:00) A: cnr-ibf-pa/hbp-bsp-issues <hbp-bsp-issues@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: Re: [cnr-ibf-pa/hbp-bsp-issues] Validation usecases: Unnecessary package installs  (#463) This was intended. Some temporary patchwork was required to make the usecases run while the KG backend isn't completely ready (minor API changes to be made/tested).
Once the APIs are completely ready, I will make a new pip release and update the first cell in the usecase notebooks to reflect the latest version number.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/463?email_source=notifications\u0026email_token=AGWBC56JKWOXTCNCYTFHVCTQMS3V7A5CNFSM4ITRNWT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFEBSY#issuecomment-537542859",
"url": "https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/463?email_source=notifications\u0026email_token=AGWBC56JKWOXTCNCYTFHVCTQMS3V7A5CNFSM4ITRNWT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFEBSY#issuecomment-537542859",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rmiglior** [comment]
Inviato da smartphone Samsung Galaxy.
a-------- Messaggio originale --------Da: appukuttan-shailesh <notifications@github.com> Data: 02/10/19  17:18  (GMT+01:00) A: cnr-ibf-pa/hbp-bsp-issues <hbp-bsp-issues@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: Re: [cnr-ibf-pa/hbp-bsp-issues] Validation usecases: Unnecessary package installs  (#463) This was intended. Some temporary patchwork was required to make the usecases run while the KG backend isn't completely ready (minor API changes to be made/tested).
Once the APIs are completely ready, I will make a new pip release and update the first cell in the usecase notebooks to reflect the latest version number.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/463?email_source=notifications\u0026email_token=AGWBC56JKWOXTCNCYTFHVCTQMS3V7A5CNFSM4ITRNWT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFEBSY#issuecomment-537542859",
"url": "https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/463?email_source=notifications\u0026email_token=AGWBC56JKWOXTCNCYTFHVCTQMS3V7A5CNFSM4ITRNWT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAFEBSY#issuecomment-537542859",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by appukuttan-shailesh** [comment]
Resolved.

**Comment by alex4200** [comment]
yes done
