### ISSUE TITLE
Review: Guidebook for Feature Extraction

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#47]
I made a first review of the documentation for "Trace Analysis" available on the Guidebook in the BSP at https://collab.humanbrainproject.eu/#/collab/1655/nav/18580. 

Generally, the documentation seems to be well written and explains the use case workflow really good and precise; however I found some typos and some minor points (see screenshot):

1. The first paragraph in "HBP database" is not quite clear to me. Especially what the meaning of "authorized collabs" mean. 
1. The section in "Feature extraction" is not clear to me. Maybe its clear to a scientist using this use case, but do not quite understand the ongoing 'averaging'...
1. Same section: Providing an email of a person does not seem to be the right thing to me. It should be a general email address in case the person changes the project etc.
1. When selecting a trace from the HBP database I see many "unknown" I can select. Why is that?
1. After the trace selection screen there is currently a kind of validation screen which does not 'look very clear'. Maybe this is just a temporary screen? 

Thanks for clarifications...

![fireshot capture 1 - feature extraction graphical user inte_ - https___lbologna github io_hbp-sp6-](https://user-images.githubusercontent.com/12729291/32178882-30af6116-bd8e-11e7-9271-95caf8987308.png)

**Comment by alex4200** [comment]
until end of the week (8.12.2017)

**Comment by lbologna** [comment]
Hello, 
I corrected the typos and addressed the 5 points in the following way:

_1. The first paragraph in "HBP database" is not quite clear to me. Especially what the meaning of "authorized collabs" mean._
I changed the text in order for it to be clearer.

_2. The section in "Feature extraction" is not clear to me. Maybe its clear to a scientist using this use case, but do not quite understand the ongoing 'averaging'..._
I changed the text in order for it to be clearer.

_3. Same section: Providing an email of a person does not seem to be the right thing to me. It should be a general email address in case the person changes the project etc._
I changed the provided email address.

_4. When selecting a trace from the HBP database I see many "unknown" I can select. Why is that?_
I wrote an explanatory sentence for this in the "Trace Selection" section of the Guidebook.

_5. After the trace selection screen there is currently a kind of validation screen which does not 'look very clear'. Maybe this is just a temporary screen?_
I modified the upload panel so that now it should be clearer to the user that, after browsing for the data, the "Upload" button must be pressed in order for the files to be actually uploaded.

Could you please check on the official app and guidebook?

Thanks.

**Comment by alex4200** [comment]
All fine
