### ISSUE TITLE
Service Account - Import endpoint

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#518]
I need to use the functionality [Import](https://www.unicore.eu/docstore/ucc-7.8.0/ucc-manual.html#_job_data_management) from Unicore to retrieve the Simulation results for an analysis.

I have updated the [notebook](https://collab.humanbrainproject.eu/#/collab/77074/nav/521705) with the part `Analysis` in there I describe more or less the process and I provide example working with PizDaint (not the Service Account)

I would need a new endpoint `https://bspsa.cineca.it/advanced/pizdaint/services/`
Please check the notebook due there there are more details.

**Comment by rcsm17** [comment]
I modify the endpoint to accept 'services' as well.
I run the analysis and without any changes the job won't run due to the "imports_array" you pass in the job payload, indeed these imports point to **"https://bspsa.cineca.it/advanced/pizdaint/services/..."** instead of **"https://brissago.cscs.ch:8080/DAINT-CSCS/services/..."**.
Changing these urls with the original one allow the job to run without errors.

**Comment by antonelepfl** [comment]
Unfortunately, I'm not quite sure to understand you comment.
The import fetches from the same endpoint that you launch the jobs.

I tried to run the notebook changing the endpoint on the top (instead of `https://brissago.cscs.ch:8080/DAINT-CSCS/rest/core` use `https://bspsa.cineca.it/advanced/pizdaint/rest/core` and it does not seems to work.

How did you test it to work?

**Comment by rcsm17** [comment]
So, when you put the import on the job payload, you pass it the url as "https://bspsa.cineca.it/advanced/pizdaint/services/..." but on pizdaint it must be "https://brissago.cscs.cs:8080/DAINT-CSCS/services/...." otherwise it returns some errors. 
Now I modified the request on SA to change the payload urls if it find the "Import" key on the job payload and you can run the notebook example without make change.

**Comment by alex4200** [comment]
@rcsm17 Is there any news on this item?

**Comment by rcsm17** [comment]
Hi @alex4200, I think it works.
The notebook jupyter I used as test and provided by @antonelepfl seems to work. 
I run also the [Simulation launcher gui](https://bbp.epfl.ch/public/alpha.simulationapp/dist/index.html#/circuits/hippo_mooc_sa_microcircuit) and I'm not sure but I think it works. too

**Comment by alex4200** [comment]
Test simulation and Test analysis on the alpha SimUI did work using the new SA endpoint.

**Comment by antonelepfl** [comment]
Thank you a lot Roberto!
So far I was able to run the simulation and analysis correctly !
I'll close this issue and let you know if I find any other issue. Thanks for the hard work

**Comment by rcsm17** [comment]
You're welcome Stefano ! 
I'm glad it works well.
