### ISSUE TITLE
Piz-Daint - CPUsPerNode not available

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#524]
### Expected behavior
Submit job in Piz-Daint works specifying `CPUsPerNode` as before (yesterday it was working).

### Actual Behavior (please include screenshot if possible)
I get
```...failed: Resource <CPUsPerNode> is not available at this site```
![Screenshot 2020-02-12 at 08 47 26](https://user-images.githubusercontent.com/24406041/74314038-0ba38680-4d75-11ea-8408-f508c7b7f008.png)

### Steps to reproduce the problem
Launch a job with the payload 
```
{
   "Name":"Cells - 3Nodes - 1H - LFP",
   "Executable":"/bin/bash input.sh",
   "haveClientStageIn":"true",
   "Resources":{
      "Nodes":3,
      "CPUsPerNode":36,
      "Runtime":3600,
      "NodeConstraints":"mc",
      "Memory":"64000M",
      "CPUs":108
   },
   "Tags":[
      "simulation",
      "hippo_hbp_full_ca1",
      "lfp_simulation"
   ]
}
```

@BerndSchuller do you have any clue ?

**Comment by clupascu** [comment]
@antonelepfl my jobs are failing since yesterday evening too. I get 

HTTP Error: 500 Server Error

</h1>Error reason:\n<pre>    Server Error</pre><h3>Caused by:</h3>

javax.servlet.ServletException: Failed to process POST request: javax.servlet.ServletException: The request doesn&apos;t look like a valid SOAP request.

So maybe the unicore server is down. I just opened a ticket at support. I will let you know. Maybe we can discuss this at the joint platform meeting today.

**Comment by clupascu** [comment]
For me unicore on PizDaint works again properly. @antonelepfl you can try again.

**Comment by antonelepfl** [comment]
Yeah so far is working again! Thank you for the update
