### ISSUE TITLE
Cerebellum Use Cases - Adding suggestion

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#534]
Hi @Helveg, @alberto-antonietti, @AliceGem

I see that you are adding some Use Cases of the Cerebellum.
Just to have in mind for helping you with the Pull Requests and be on the same page, I would like to know if you all agree that instead of creating new items on the root (brainareacircuitinsilicoexperiments) which gives us something like:

![Screenshot 2020-03-26 at 09 52 31](https://user-images.githubusercontent.com/24406041/77627886-e09d7c80-6f47-11ea-9c5f-28e44ce6b1bb.png)

As all of your use cases are based on Cerebellum, I would suggest to keep the first page clean dividing by region (Hippocampus, Cerebellum, etc):

![Screenshot 2020-03-26 at 09 53 39](https://user-images.githubusercontent.com/24406041/77628013-075bb300-6f48-11ea-95d0-28837a8f9656.png)

And when you click on Cerebellum, you see your use cases. Something like:

![Screenshot 2020-03-26 at 10 01 21](https://user-images.githubusercontent.com/24406041/77628754-c617d300-6f48-11ea-842c-b2c25417ac32.png)

Do you all agree to proceed moving your use cases inside the Cerebellum category?
I can make the changes required on each PR but I would need to have your agreement.

**Comment by AliceGem** [comment]
Hi @antonelepfl for the one I opened, it's fine, I agree! I should have already put it as an item of the dictionary `models`, inside "Cerebellum", but maybe I did it wrong. Thanks a lot!

**Comment by alberto-antonietti** [comment]
Hi Stefano,
This is a good suggestion, but for my UC (Cerebro-Cerebellar Loops) I would not put it under a "Cerebellum" group, since it involves both the cerebellum and other cortical areas (e.g., it is referenced from this page https://www.humanbrainproject.eu/en/brain-simulation/whole-mouse-brain-model/).
We can use a different image to distinguish it from the general "Cerebellum" UCs, if you think that this could confuse the users.

**Comment by Helveg** [comment]
@antonelepfl  That's what I was going for, just like Alice, but must've misunderstood the instructions.

**Comment by antonelepfl** [comment]
Great then, thank you.
