### ISSUE TITLE
HHNB use case with PizDaint generates an error

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#543]
### Expected behavior

I am able to select the "Hodgkin-Huxley Neuron Builder" usecase and use PizDaint as the computer system.

### Actual Behavior (please include screenshot if possible)

When I create a simulation with PizDaint I get the error "Submission ended with error: Operation not completed"

### Optional infrastructural data (user, platform, browser, environment, ...)

PROD

**Comment by alex4200** [comment]
@lbologna can have a look by 15.5.2020.

**Comment by alex4200** [comment]
@lbologna  The notebooks seem to be back running.

**Comment by alex4200** [comment]
Update from @lbologna : On DEV the use of PizDaint might work again, but the results returned are invalid.

**Comment by lbologna** [comment]
Everything seems to work now. The latest problem was probably due an old optimization file that we were using for testing and that was generated before the latest modification done to the optimization dataset. I added an example .zip file in the Guidebook page so that users are guided in creating their own model.
Here's the link to the guidebook page:
https://humanbrainproject.github.io/hbp-sp6-guidebook/online_usecases/single_cell_building/hippocampus/p1_hh_neuron_builder/p1_hh_neuron_builder.html

@alex4200 could you please have a look at both web app and guidebook before closing the ticket?
Everything is in prod already.
Thank you.

**Comment by alex4200** [comment]
With the new example file it seems to work fine with PizDaint and Service Account, closing ticket
