### ISSUE TITLE
Update of Jupyter notebook on 6 December

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#98]
There will be an update of the jupyter notebooks next week (6 December) which might break existing notbooks. Release notes are here:

https://collab.humanbrainproject.eu/#/collab/509/nav/46218

Everybody involved in a notebook needs to check if the notebook is ready for the changes...

**Comment by clupascu** [comment]
I am in contact with the collab team. In my notebooks there are a few problems. I am already testing the notebooks in the dev environment where the new image of the jupyter notebook is already installed.

**Comment by mmigliore** [comment]
Just to be clear:
I do not think it is not our responsibility to check and solve for  
problems generated by a new release of any of the collaboratory  
components, including notebooks.
It is up to the collaboratory people to be sure that any new release  
does not have compatibillity issues with the current public notebooks  
and apps.

Of course we can help them in solving the issues BEFORE the release  
but doing this AFTER, because a release date is decided without a  
complete check for problems, is a perfect recipe for a disaster.

We are in contact with them, and they know of a series of major  
problems with jupyter notebooks. Basically all notebooks with any sort  
of GUI will simply not work anymore, and the solutions do not appear  
to be quick and/or simple.

Cheers
Michele



alex4200 <notifications@github.com> ha scritto:

**Comment by clupascu** [comment]
I fixed the notebooks to "work" after the platform update. As suggested in a previous email from the platform, the new version of ipywidgets is not entirely backward compatible with the version that was previously available in the notebooks. Therefore, this upgrade has side effects on my notebooks.

They suggested to use the code below

https://collab.humanbrainproject.eu/#/collab/509/nav/46468

in order to downgrade the ipywidgets version, until I am able to write a code for my notebooks compatible with the latest installed ipywidgets version.

You can test now again my notebooks.

**Comment by alex4200** [comment]
@clupascu : In order to avoid the issues with ipywidgets on a notebook alltogether: What about using a proper GUI for at least some of the use cases? Have you given that a thought? Would it be too much work? What is your view on this?

**Comment by clupascu** [comment]
What do you mean with proper GUI?

**Comment by alex4200** [comment]
Like in "Feature Extraction" for example

**Comment by clupascu** [comment]
That means creating an app instead of a notebook. Maybe at the end we will get there. But this means not using the notebooks anymore.

**Comment by jdcourcol** [comment]
I agree with @clupascu . We may get to replace the notebook with dedicated app. but there are time and resources constraints for the March 2018 deadline for everyone.

**Comment by alex4200** [comment]
I think all issues related to the update are fixed or reported in other issues. Closing now
